### ISSUE TITLE
Broken Newest Chrome 49.0.2623.87

### ISSUE THREAD

**Issue by dirwin517** [janodvarko/harviewer#57] opened 2016-03-09 18:40 UTC
harViewer.js:1 
Uncaught SyntaxError: Identifier 'Pie' has already been declared

**Comment by gitgrimbo** [comment] 2016-03-10 08:38
Which browser does this happen in?  Do you have a sample HAR file?  Did the error on the public viewier (http://www.softwareishard.com/har/viewer/)?

When the error happens, can you open the Chrome/Firefox devtools and pretty print the code for `harViewer.js` to find a better line number and the exact failing code?

Need more information please.

**Comment by dirwin517** [comment] 2016-03-10 14:08
The Page fails to load, so no har needed, no content visible

Pretty Print shows 
Uncaught SyntaxError: Identifier 'Pie' has already been declared harViewer.js:formatted:3511

which is related to the Pie declaration on line 3422


[harViewer.txt](https://github.com/janodvarko/harviewer/files/167248/harViewer.txt)

**Comment by gitgrimbo** [comment] 2016-03-11 00:01
Think this is a duplicate of #50 (HAR Viewer redeclares functions; not ES6 compatible).

**Comment by riccardoroasio** [comment] 2016-04-04 08:38
Hi,

I found a solution (maybe temporary...) to fix the problem:

Simply in harViewer.js change this:

` function Pie() {}
   Pie.prototype = {`

to this:

` function PieF() {}
   PieF.prototype = {`


and subtitute all calls like this :

`Lib.extend(Pie.prototype,`

to this:

`Lib.extend(PieF.prototype,`


Hope this can helps,

Riccardo Roasio

**Comment by janodvarko** [comment] 2016-04-04 09:43
Isn't this already fixed by https://github.com/janodvarko/harviewer/commit/1eee20fa802623182d5618056584983041124e28
?

It should also be deployed here:
http://www.softwareishard.com/har/viewer/

When I load that page in Chrome it seems to be working for me.

Honza

**Comment by gitgrimbo** [comment] 2016-04-04 20:24
Chrome 49.0.2623.110 m works for me now as well.  But when the issue was raised I saw the same error in Chrome.

Has there been a deployment to http://www.softwareishard.com/har/viewer/ since 9th March?

**Comment by gitgrimbo** [comment] 2016-05-24 20:44
@dirwin517, can this be closed now?  Are you still seeing the issue?

**Comment by dirwin517** [comment] 2016-05-24 21:26
@gitgrimbo looks good to me

**Comment by gitgrimbo** [comment] 2016-05-24 21:47
Great!  Are you able to close the issue pls?  Cheers.

**Closed** 2016-05-24 21:55 UTC

**Comment by dannydong** [comment] 2016-05-31 06:53
Hi all,

I run into the same issue with the HAR Viewer 2.0.17 (release package, 2 months ago): 
error message: harViewer.js:1 Uncaught SyntaxError: Identifier 'Pie' has already been declared on Chrome 49.0.2623.112 m
Do I need to rebuild it after I download the latest zip package from github?

**Comment by dannydong** [comment] 2016-05-31 07:46
run ant build with error:
BUILD FAILED
D:\Software\test_tool\Web\harviewer-master_2016.5.31\harviewer-master\build.xml:140: Execute failed:
 java.io.IOException: Cannot run program "node" (in directory "D:\Software\test_tool\Web\harviewer-m
aster_2016.5.31\harviewer-master\webapp\scripts"): CreateProcess error=2, The system cannot find the
 file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.j
ava:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:426)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:440)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 23 more

**Comment by gitgrimbo** [comment] 2016-05-31 07:57
Does the website http://www.softwareishard.com/har/viewer/ work for you?

For your build issue, the default `r.js` optimisation now uses [Node.JS](https://nodejs.org/en/download/), so this needs to be installed.  Alternatively, you should still be able to use Java for the JS optimisation.  Can you try passing this parameter at the command line:

    ant -Drjs.runner=java build

**Comment by dannydong** [comment] 2016-05-31 15:28
The website works for me, but the code doesn't work for my local web server.
Thanks a lot, man, I will try to build it.

**Comment by gitgrimbo** [comment] 2016-05-31 18:49
Just tried `ant -Drjs.runner=java build` and it hangs for me.  I waited about 20 seconds and it was stuck here:

     [java] Tracing dependencies for: harViewer
     [java]
     [java] Tracing dependencies for: harPreview
     [java] Uglify file: D:/dev/git_repos/harviewer2/webapp-build/har.js

Running [jvisualvm](http://docs.oracle.com/javase/6/docs/technotes/guides/visualvm/applications_local.html) I could attach to the `org.mozilla.javascript.tools.shell.Main` code and saw this:

![harviewer-57-jvisualvm](https://cloud.githubusercontent.com/assets/1020541/15686411/0fc1a06c-2768-11e6-96c6-e1c59455f1a1.png)

so a lot of time is being burnt up in the [r.js](https://github.com/requirejs/r.js) code (top row in the Hot Spots).

I'll try and work out what's going wrong, but I would strongly recommend installing Node.JS and using the default build, not the Java build.

**Comment by gitgrimbo** [comment] 2016-05-31 20:01
Raised separate issue #69 (*Java build broken?*) for @dannydong.

This issue can remain closed as the 2.0.17 build works as expected.
