### ISSUE TITLE
pagespeed.exe

### ISSUE THREAD

**Issue by workingstudent2017** [janodvarko/harviewer#91] opened 2016-08-12 11:08 UTC
I tried to setup a .Net winForm within a button to start the pagespeed.exe.
Here are the following line of code?

hope somebody can support me :-)

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;

namespace Test_HAR_Projekt
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Process p = new Process();
            Process proThis = new Process();
            ProcessStartInfo psiThis = new ProcessStartInfo(@"C:\Users\Desktop\BT_Arbeit\har_to_pagespeed.exe");
            psiThis.Arguments = "www.digitec.ch har";
            psiThis.RedirectStandardOutput = true;
            p.StartInfo.RedirectStandardInput = true;
            psiThis.UseShellExecute = false;
            //proThis.StartInfo = psiThis;
            //proThis.Start();
            //p.StandardInput.WriteLine(@"cd C:\Users\Desktop\BT_Arbeit>har_to_pagespeed.exe www.digitec.ch.har");
            //p.StandardInput.WriteLine("har_to_pagespeed");
            Console.Write(proThis.StandardOutput.ReadToEnd());
            Console.ReadLine();
           //public InvalidOperationException();
        }
    }
}

**Comment by gitgrimbo** [comment] 2016-08-12 11:28
Hi, I don't think this is a valid issue to be raised against HAR Viewer. Maybe try the pagespeed support channels.

**Comment by gitgrimbo** [comment] 2016-08-16 07:56
Closing because the issue is with using pagespeed, not HAR Viewer.

**Closed by gitgrimbo** 2016-08-16 07:56 UTC
