### ISSUE TITLE
"log.pages[0].pageTimings.onLoad object value found, but a number is required"

### ISSUE THREAD

**Issue by mss** [janodvarko/harviewer#48] opened 2015-10-20 13:50 UTC
I created a HAR file with Chrome 46.0.2490.71 m (64-bit) and harviewer refuses to load it due to the error message `log.pages[0].pageTimings.onLoad object value found, but a number is required`. The JSON involved can be seen below; the page was never finished loading but cancelled instead.

If I just remove the onLoad event, the file can be opened fine. It would be great if harviewer could handle a `null` value here more gracefully.

``` json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-10-20T13:01:30.474Z",
        "id": "page_5",
        "title": "https://www.example.com/something",
        "pageTimings": {
          "onContentLoad": 21085.5520000041,
          "onLoad": null
        }
      }
    ],
    …
}
```

**Comment by gitgrimbo** [comment] 2016-06-23 20:24
Hi, sorry for the wait!

I can reproduce your findings with the following page that downloads 18 images slowly enough that I can save a HAR (in Chrome 51) before the onload event fires.  I then see `null` as the `pageTimings.onLoad` value as you do.

https://stevesouders.com/cuzillion/?c0=bi1hfff2_0_f&c1=bi1hfff2_0_f&c2=bi1hfff2_0_f&c3=bi1hfff2_0_f&c4=bi1hfff2_0_f&c5=bi1hfff2_0_f&c6=bi1hfff2_0_f&c7=bi1hfff2_0_f&c8=bi1hfff2_0_f&c9=bi1hfff2_0_f&c10=bi1hfff2_0_f&c11=bi1hfff2_0_f&c12=bi1hfff2_0_f&c13=bi1hfff2_0_f&c14=bi1hfff2_0_f&c15=bi1hfff2_0_f&c16=bi1hfff2_0_f&c17=bi1hfff2_0_f&t=1466712532833

The resulting HAR *can* be loaded if you turn validation off.  Is that not a valid enough workaround do you think?  I'm not sure what the original principle was behind the validation, so I'm not really qualified to say if it's being too strict or not.

What I *can* say is that [the spec](http://www.softwareishard.com/blog/har-12-spec/#pageTimings) says `pageTimings.onLoad` is optional, *not* that it can be `null`.

**Firefox 47** saves the HAR as follows:

        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }

**IE11** saves the HAR as follows (in its XML format):

			<pageTimings>
				<onContentLoad>-1</onContentLoad>
				<onLoad>-1</onLoad>
			</pageTimings>

So I guess it could be concluded that Chrome is wrong and the other two browsers are doing the right thing.

@janodvarko - can you offer any advice?

**Comment by gitgrimbo** [comment] 2016-06-23 20:37
To add to my comment, the FF47 HAR generated from the above test is itself invalid.  For the responses that weren't downloaded completely, we see the following:

      {
        "pageref": "page_1",
        "startedDateTime": "2016-06-23T21:15:36.761+01:00",
        "time": null,
        ...
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": -1
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1
        },
        "timings": {}

These are the errors:

    log.entries[2].time                       object value found, but a number is required
    log.entries[2].response.content.mimeType  is missing and it is not optional
    log.entries[2].timings.send               is missing and it is not optional
    log.entries[2].timings.wait               is missing and it is not optional
    log.entries[2].timings.receive            is missing and it is not optional

**Comment by mss** [comment] 2016-06-23 21:30
Yes, I ran into lots of HAR files which weren't viewable with harviewer because reality didn't match the spec and at some point just stopped using it. I don't see the point in validating the input, IMO it should be displayed as far as possible *shrug*

**Comment by gitgrimbo** [comment] 2016-06-23 21:51
Could you give any examples of HARs that weren't viewable?

From my experience, although some HARs will not validate, once you have turned off validation the viewer does a decent job of previewing most HARs.

For example, the invalid Chrome51 and Firefox47 HARs I mentioned do not validate, but both can be previewed.

**Comment by mss** [comment] 2016-06-24 05:36
I had another look at the harviewer page and I think I confused the tools, sorry. It is just too long ago.

**Comment by gitgrimbo** [comment] 2016-06-24 21:49
Sure, no problem.  Do you think there's value in leaving this issue open just in case, or is it resolved?

I've been able to load HARs that have content matching your example once I turn validation off (unchecking the check box).

![harviewer-48](https://cloud.githubusercontent.com/assets/1020541/16351459/b9a6dc0c-3a5d-11e6-99a2-cd3895ee989d.png)

**Comment by mss** [comment] 2016-06-25 09:31
If it loads now, I think it is fixed so the issue can be closed.

IMO the default mode should be more lenient though and cope better with real world examples. That could mean a default-off checkmark for validation or maybe a less strict mode which both handles null values as absent keys and copes with non-essential non-optional fields missing while still doing some basic sanity checks. But that's just my opinion :-)

**Comment by gitgrimbo** [comment] 2016-07-04 22:27
Thanks @mss for your input.  I'm intending to close this as "works as expected" because invalid HARs can be loaded by turning off validation with the checkbox, and HAR Viewer also does its best to preview invalid HARs.

It looks like a browser issue that invalid HARs are exported.  @janodvarko - Do you have any Firefox knowledge that could explain [these results](https://github.com/janodvarko/harviewer/issues/48#issuecomment-228176064)?

**Comment by jaraco** [comment] 2017-06-02 15:40
I've encountered this issue. I found that when using the drag/drop feature, one not only has to uncheck the box for validation, but also reload the app before dropping the file. Otherwise, it will attempt validation anyway.

**Comment by gitgrimbo** [comment] 2017-06-05 10:59
Hi @jaraco, you definitely need to uncheck the box to disable validation, but I didn't think you had to reload the app.  That doesn't sound like the proper user experience to me.

**Comment by gitgrimbo** [comment] 2018-06-11 13:43
Cannot reproduce the issue with current HAR Viewer (master).

1. Clear browser cache.
2. drag-n-drop the following JSON file onto HAR Viewer.
3. HAR Viewer complains that the JSON is invalid according to the HAR schema, and shows an error on the *Preview* tab (as `onLoad` is invalid type. This is correct behaviour).
4. Untick the validate checkbox on the *Home* tab.
3. drag-n-drop the following JSON file onto HAR Viewer.
5. HAR Viewer shows the page in the *Preview* tab (with no entries, as there are no entries. This is correct behaviour. See screenshot below).

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-10-20T13:01:30.474Z",
        "id": "page_5",
        "title": "https://www.example.com/something",
        "pageTimings": {
          "onContentLoad": 21085.5520000041,
          "onLoad": null
        }
      }
    ],
    "entries": []
  }
}
```

![image](https://user-images.githubusercontent.com/1020541/41235017-b87699dc-6d85-11e8-9554-c8cdd98fbfa5.png)

**Closed by gitgrimbo** 2018-06-11 13:43 UTC
